services:
  mongodb:
    image: mongo:jammy
    # environment:
      # - MONGO_INITDB_ROOT_USERNAME=user
      # - MONGO_INITDB_ROOT_PASSWORD=pass

  user-api:
    image: node:20.10-alpine
    working_dir: /app
    command: npm run dev
    volumes:
      - ./:/app
    environment:
      - MONGO_URL=mongodb://mongodb/users
      - PORT=3000
    ports:
      - 3000:3000
    depends_on:
      - mongodb
