services:
  mongodb:
    image: mongo:7.0.8-jammy
    volumes:
      - ./data:/data/db
    restart: always
  library-api:
    image: cyrillaz/api-library:0.3
    volumes:
      - ./lib:/app/lib 
    environment:
      - UPLOAD_FOLDER=lib
      - MONGO_URL=mongodb://mongodb/library
      - PORT=3000
    ports:
      - 3000:3000
    depends_on:
      - mongodb
