services:

  mongodb:
    image: mongo:7.0.8-jammy
    restart: always
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=user
    #   - MONGO_INITDB_ROOT_PASSWORD=pass

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
  library-api:
    image: node:20.10
    working_dir: /app
    command: npm run dev
    volumes:
      - ./:/app
      - ./lib:/app/lib 
    environment:
      - UPLOAD_FOLDER=lib
      - MONGO_URL=mongodb://mongodb/library
      - PORT=3000
    ports:
      - 3000:3000
    depends_on:
      - mongodb
