services:
  mongodb:
    image: mongo:jammy
    # environment:
      # - MONGO_INITDB_ROOT_USERNAME=user
      # - MONGO_INITDB_ROOT_PASSWORD=pass

  user-api:
    image: node:20.10-alpine
    working_dir: /app
    command: npm run start
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=production
      - SESSION_SECRET=XCjynKV8
      - MONGO_URL=mongodb://mongodb/users
      - PORT=3000
    ports:
      - 80:3000
    depends_on:
      - mongodb
