services:

  mongodb:
    image: mongodb/mongodb-community-server:latest
    # environment:
      # - MONGO_INITDB_ROOT_USERNAME=user
      # - MONGO_INITDB_ROOT_PASSWORD=pass

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/

  storage:
    image: redis
    volumes:
      - ./data:/data
  counter:
    image: cyrillaz/counter
    environment:
      - PORT=3001
      - REDIS_URL=redis://storage
    depends_on:
      - storage
  library:
    image: node:20.10-alpine
    working_dir: /app
    command: npm run dev
    volumes:
      - ./:/app
    environment:
      - MONGO_URL=mongodb://mongodb/library
      - COUNTER_URL=http://counter:3001/
      - PORT=3000
    ports:
      - 3000:3000
    depends_on:
      - mongodb
